on: [push]

name: Deploy Cruise Track Planner Shiny App

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    env:
      SHINYAPPS_TOKEN: ${{secrets.SHINYAPPS_TOKEN}}
      SHINYAPPS_SECRET: ${{secrets.SHINYAPPS_SECRET}}    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        install.packages(c("rsconnect"), type = "binary")
      shell: Rscript {0}

    - name: Deploy to Shinyapps.io
      run: |
        rsconnect::setAccountInfo(name = 'seaflow',
                                  token = '${{secrets.SHINYAPPS_TOKEN}}',
                                  secret = '${{secrets.SHINYAPPS_SECRET}}')
        rsconnect::deployApp(appName = 'cruisetrackplanner', account = 'seaflow', server = 'shinyapps.io', forceUpdate = TRUE)
      shell: Rscript {0}   
