on: [push]

name: Deploy Cruise Track Planner Shiny App

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        install.packages("rsconnect", type = "binary")

    - name: Deploy to Shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{secrets.SHINYAPPS_TOKEN}}
        SHINYAPPS_SECRET: ${{secrets.SHINYAPPS_SECRET}}   
      run: |
        rsconnect::setAccountInfo(name = 'seaflow',
                                  token = Sys.getenv("SHINYAPPS_TOKEN"),
                                  secret = Sys.getenv("SHINYAPPS_SECRET")
                                  )
        rsconnect::deployApp(appName = 'cruisetrackplanner', server = 'shinyapps.io', forceUpdate = TRUE)
