on: [push]

name: Deploy Cruise Track Planner Shiny App

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_TOKEN: ${{A33504145BE69558791A701B7385E178}} 
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install rsconnect
        run: install.packages('rsconnect')
      - name: Deploy to Shinyapps.io
        run: |
          rsconnect::setAccountInfo(name='seaflow',
                                   token='${{ secrets.SHINYAPPS_TOKEN }}',
                                   secret='﻿﻿﻿2nZ22Y34g43gxF4THf4uNGMl1zhFIo4rsJT1dyWx')
          rsconnect::deployApp(appName = 'cruisetrackplanner')
