on: [push]

name: Deploy Cruise Track Planner Shiny App

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }} 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies 
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcurl4-openssl-dev 

    - name: Install R dependencies
      run: Rscript -e 'install.packages(c("curl", "rsconnect"), repos="https://cloud.r-project.org")' 

    - name: Deploy to Shinyapps.io
      run: |
        Rscript -e "rsconnect::deployApp(appName = 'cruisetrackplanner', account = 'seaflow', 
                                     token = '${{ secrets.SHINYAPPS_TOKEN }}', 
                                     secret = '${{ secrets.SHINYAPPS_SECRET }}')"
