on: [push]

name: Deploy Cruise Track Planner Shiny App

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }} 
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install rsconnect
        run: install.packages('rsconnect')
      - name: Deploy to Shinyapps.io
        run: |
          rsconnect::setAccountInfo(name='your_shinyapps_username',
                                   token='${{ secrets.SHINYAPPS_TOKEN }}',
                                   secret='your_shinyapps_secret')
          rsconnect::deployApp(appName = 'your_shiny_app_name')
